import './globals.css';
import styles from './layout.module.css';
import { Roboto, Noto_Sans_JP } from 'next/font/google';
import Logo from '@/img/logo.svg';

export const metadata = {
  title: 'hello world',
  description: 'Generated by Next.js',
}

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '600', '800'],
  variable: '--font-roboto',
});

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['300', '400', '600', '800'],
  variable: '--font-noto-sans-jp',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body
        className={`${roboto.variable} ${notoSansJP.variable}`}
      >
        <nav
          className={styles.nav}
        >
          <h2>
            <Logo height="1.5em" />
            AtsuoCoder
          </h2>
        </nav>

        <div
          className={styles.main}
        >
          {children}
        </div>
      </body>
    </html>
  )
}